---
version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: webapp/scripts/stop_server.sh
      timeout: 300
      runas: root
    - location: webapp/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: webapp/scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: webapp/scripts/start_server.sh
      timeout: 300
      runas: root
